project:
  type: website

website:
  page-navigation: true
  title: "DSC 223 - Fall 2022 - Block 2 "
  description: "Homepage for DSC 223 - Introudction to Data Science at Cornell College, Fall 2022."
  site-url: "https://dsc223-fb2-2022.github.io/website/"

  repo-url: https://github.com/DSC223-FB2-2022/website
  repo-actions: [edit, issue]

  open-graph: true

  twitter-card:
    creator: "@stats_tgeorge"
    image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Tyler George"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    # logo: "images/logo.png" # This is where I put my hex
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/DSC223-FB2-2022/website
        text: "GitHub organization"
      - icon: code-square
        href: http://turing.cornellcollege.edu:8787/
        text: "RStudio Server"
      - icon: person-fill
        text: "Moodle"
        menu:
          - text: Announcements
            url: https://moodle.cornellcollege.edu/mod/forum/view.php?id=239844
          - text: Gradebook
            url: https://moodle.cornellcollege.edu/grade/report/user/index.php?id=6992
          - text: Homepage
            url: https://moodle.cornellcollege.edu/course/view.php?id=6992

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-instructor.qmd
            text: Instructor
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
      - section: "Supplementary Documents"
        contents:
          - href: course-materials/documents

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

execute:
  freeze: auto