---
title: "DSC 223: Introduction to Data Science"
tbl-colwidths: [3,7,15,3,3,3,10,5,5]
---

This page contains an outline of the topics, content, and assignments for the block. Note that this schedule will be updated as the block progresses, with all changes documented here.

::: column-screen-inset-right
| Day | Date         | Topic                                                                                                                                                      |                                                                                                                                                                               Slides                                                                                                                                                                                |   AE   |                                               Lab                                               | HW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | Exam |                Project                 |
|:-----:|-------|---------|:--------:|:-----:|:-----:|:-----------------|:-----:|:-----------:|
|  1  | Mon, Sep 26  | Welcome and Toolkit <br/> Data Viz                                                                                                                         |                                              [🖥️](/course-materials/_slides/u1-d01-welcome/u1-d01-welcome.pdf "u1-d01-welcome")[🖥️](/course-materials/_slides/u1-d02-toolkit-r/u1-d02-toolkit-r.pdf "u1-d02-toolkit-r")[🖥️](/course-materials/_slides/u1-d03-toolkit-git/u1-d03-toolkit-git.pdf "u1-d03-toolkit-git")                                               | 📋📋📋 |    [💻](/course-materials/lab-instructions/lab-01/lab-01-hello-r.html "Lab 01 Instructions")    | [📖 Chp 2 R4ds](https://r4ds.had.co.nz/explore-intro.html "Read Chapter 2 R4ds") <br/> [📖 Sec 1.1,1.2 IMS](https://openintro-ims.netlify.app/data-hello.html "Sec 1.1,1.2 IMS") <br/> [📖 Chp 3 R4ds](https://r4ds.had.co.nz/data-visualisation.html "Read Chapter 2 R4ds") <br/> Read [CARVE](/course-materials/documents/CARVE.pdf) <br/> [Start HW 01 ✍️](/course-materials/hw-instructions/hw-01/hw-01-pet-names.html "Your version available via GitHub")                                                                              |      |                                        |
|  2  | Tue, Sep 27  | Tidy Data <br/> Data wrangling <br/> Data Frame                                                                                                            |             [🖥️](/course-materials/_slides/u2-d01-data-viz/u2-d01-data-viz.pdf "u2-d01-data-viz")[🖥️](/course-materials/_slides/u2-d02-ggplot2/u2-d02-ggplot2.pdf "u2-d02-ggplot2")[🖥️](/course-materials/_slides/u2-d03-viz-num/u2-d03-viz-num.pdf "u2-d03-viz-num")[🖥️](/course-materials/_slides/u2-d04-viz-cat/u2-d04-viz-cat.pdf "u2-d04-viz-cat")             |   📋   |    [💻](/course-materials/lab-instructions/lab-01/lab-01-hello-r.html "Lab 01 Instructions")    | [Finish HW 01](/course-materials/hw-instructions/hw-01/hw-01-pet-names.html)[✍️](/course-materials/hw-instructions/hw-01/hw-01-pet-names.html "Your version available via GitHub") <br/> [📖 Chp 4 IMS](https://openintro-ims.netlify.app/explore-categorical.html "Sec 1.1,1.2 IMS") <br/> [📖 Chp 5 IMS](https://openintro-ims.netlify.app/explore-numerical.html "Read Chapter 2 R4ds") <br/> [📖 The Ethical Data Scientist](https://slate.com/technology/2016/02/how-to-bring-better-ethics-to-data-science.html "Read Chapter 2 R4ds") |      |                                        |
|  3  | Wed, Sep 28  | [📋 Ethical DS Ethics Discussion.](/course-materials/class-discussion/ethical_ds_discussion.qmd) <br/> Practice Tuesday content. <br/> No afternoon class. |                                                                                                                                                                                None                                                                                                                                                                                 |        | [💻](/course-materials/lab-instructions/lab-02/lab-02-plastic-waste.html "Lab 02 Instructions") | [📖Tidy data](https://www.jstatsoft.org/article/view/v059i10) <br/> [📖 Chp 13 R4ds](https://r4ds.had.co.nz/relational-data.html) <br/> [📖 Chp 12 R4ds](https://r4ds.had.co.nz/tidy-data.html) <br/> [📖 Gelman](http://www.stat.columbia.edu/~gelman/research/published/ChanceEthics14.pdf) <br/> [📖ASA Guidelines](https://www.amstat.org/your-career/ethical-guidelines-for-statistical-practice) [✍️Complete HW 02](/course-materials/hw-instructions/hw-02/hw-02-airbnb-edi.html "Your version available via GitHub")                 |      |                                        |
|  4  | Thu, Sep 29  | Tidy data, wrangling, and data frames                                                                                                                      |                                     [🖥️](/course-materials/_slides/u2-d05-tidy-data/u2-d05-tidy-data.pdf "u2-d05-tidy-data")[🖥️](/course-materials/_slides/u2-d06-grammar-wrangle/u2-d06-grammar-wrangle.pdf "u2-d06-grammar-wrangle")[🖥️](/course-materials/_slides/u2-d07-single-df/u2-d07-single-df.pdf "u2-d07-single-df")                                      |   📋   |                                                                                                 | [📖Chp 15 R4ds](https://r4ds.had.co.nz/factors.html) <br/>[✍️ Complete HW 03](/course-materials/hw-instructions/hw-03/hw-03-accidents.html "Your version available via GitHub")                                                                                                                                                                                                                                                                                                                                                              |      |        📂Project Group Meeting         |
|  5  | Fri, Sep 30  | Data frames, Data type and clasess.                                                                                                                        | [🖥️](/course-materials/_slides/u2-d08-multi-df/u2-d08-multi-df.pdf "u2-d08-multi-df")[🖥️](/course-materials/_slides/u2-d09-tidying/u2-d09-tidying.pdf "u2-d09-tidying")[🖥️](/course-materials/_slides/u2-d10-data-types/u2-d10-data-types.pdf "u2-d10-data-types")[🖥️](/course-materials/_slides/u2-d11-data-classes/u2-d11-data-classes.pdf "u2-d11-data-classes") |   📋   |                                                                                                 | [📖 Chp 11 R4ds](https://r4ds.had.co.nz/data-import.html) <br/> [✍️ Work on HW 04](/course-materials/hw-instructions/hw-04/hw-04-college-majors.html "Your version available via GitHub")                                                                                                                                                                                                                                                                                                                                                    |      | 📂 Proposal Meetings. Afternoon class. |
|  6  | Mon, Oct 3   | Ethics Discussion on Gelman and ASA                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 | [✍️Finish HW 04](/course-materials/hw-instructions/hw-04/hw-04-college-majors.html "Due at 9am on Oct 4th")                                                                                                                                                                                                                                                                                                                                                                                                                                  |      |                                        |
|  7  | Tue, Oct 4   |                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |      |                                        |
|  8  | Wed, Oct 5   |                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |      |                                        |
|  9  | Thu, Oct 6   |                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |      |                                        |
| 10  | Fri, Oct 7   |                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |  ✅  |                   📂                   |
| 11  | Mon, Oct 10  |                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |      |                                        |
| 12  | Tues, Oct 11 |                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |      |                                        |
| 13  | Wed, Oct 12  |                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |      |                                        |
| 14  | Thu, Oct 13  |                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |      |                                        |
| 15  | Fri, Oct 14  |                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |      |                   📂                   |
| 16  | Mon, Oct 17  |                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |      |                                        |
| 17  | Tue, Oct 18  |                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |      |                   📂                   |
| 18  | Wed, Oct 19  | Final Exam                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                     |        |                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |  ✅  |                                        |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Slides | AE  | Labs | HW  | Exam | Project |
|------|------|-------|:------:|:---:|:----:|:---:|:----:|:-------:|
| Week | Date | Topic |   🖥️   | 📋  |      | ✍️  |  ✅  |   📂    |
