{
  "hash": "65f8eca6689d51a6647fc135e40e5a2f",
  "result": {
    "markdown": "---\ntitle: \"The Language and Fitting of Models\"\nsubtitle: \"<br><br> Data Science in a Box\"\nauthor: \"[datasciencebox.org](https://datasciencebox.org/)\"\ndate: \"October 11th, 2022\"\nformat: revealjs\nexecute:\n  echo: true\n---\n---\nformat: revealjs\n---\n\n# The Language of Models\n\n::: {.cell}\n\n:::\n\n## What is a model?\n\n## Modelling\n\n- Use models to explain the relationship between variables and to make predictions\n- For now we will focus on **linear** models (but remember there are *many* *many* other types of models too!)\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/unnamed-chunk-2-1.png){width=100%}\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/unnamed-chunk-3-1.png){width=100%}\n:::\n:::\n:::\n\n::::\n\n# Data: Paris Paintings\n\n## Paris Paintings\n\n::: {.cell}\n\n```{.r .cell-code}\npp <- read_csv(\"data/paris-paintings.csv\", na = c(\"n/a\", \"\", \"NA\"))\n```\n:::\n\n- Source: Printed catalogues of 28 auction sales in Paris, 1764 - 1780\n- Data curators Sandra van Ginhoven and Hilary Coe Cronheim (who were PhD students in the Duke Art, Law, and Markets Initiative at the time of putting together this dataset) translated and tabulated the catalogues\n- 3393 paintings, their prices, and descriptive details from sales catalogues over 60 variables\n\n## Auctions today\n\n<iframe width=\"840\" height=\"473\" src=\"https://www.youtube.com/embed/apaE1Q7r4so\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\n\n## Auctions back in the day\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/old-auction.png){width=65%}\n:::\n:::\n\n::: aside\nPierre-Antoine de Machy, Public Sale at the Hôtel Bullion, Musée Carnavalet, Paris (18th century)\n:::\n\n## Paris auction market\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/auction-trend-paris.png){width=60%}\n:::\n:::\n\n::: aside\nPlot credit: Sandra van Ginhoven\n:::\n\n## Départ pour la chasse\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/depart-pour-la-chasse.png){width=65%}\n:::\n:::\n\n## Auction catalog text {.smaller}\n\n:::: {.columns}\n\n::: {.column width=\"25%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/auction-catalogue.png){width=60%}\n:::\n:::\n:::\n\n::: {.column width=\"75%\"}\nTwo paintings very rich in composition, of a beautiful execution, and whose merit is very remarkable, each 17 inches 3 lines high, 23 inches wide; the first, painted on wood, comes from the Cabinet of Madame la Comtesse de Verrue; it represents a departure for the hunt: it shows in the front a child on a white horse, a man who gives the horn to gather the dogs, a falconer and other figures nicely distributed across the width of the painting; two horses drinking from a fountain; on the right in the corner a lovely country house topped by a terrace, on which people are at the table, others who play instruments; trees and fabriques pleasantly enrich the background.\n:::\n\n::::\n\n\n## {data-menu-title=\"Auction Data\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/painting1.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](images/painting2.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](images/painting3.png){width=70%}\n:::\n:::\n\n## Auction Data Code {.smaller}\n\n::: {.cell}\n\n```{.r .cell-code}\npp %>%\n  filter(name == \"R1777-89a\") %>%\n  glimpse()\n```\n:::\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell output.lines='23'}\n::: {.cell-output .cell-output-stdout}\n```\nRows: 1\nColumns: 61\n$ name              <chr> \"R1777-89a\"\n$ sale              <chr> \"R1777\"\n$ lot               <chr> \"89\"\n$ position          <dbl> 0.3755274\n$ dealer            <chr> \"R\"\n$ year              <dbl> 1777\n$ origin_author     <chr> \"D/FL\"\n$ origin_cat        <chr> \"D/FL\"\n$ school_pntg       <chr> \"D/FL\"\n$ diff_origin       <dbl> 0\n$ logprice          <dbl> 8.575462\n$ price             <dbl> 5300\n$ count             <dbl> 1\n$ subject           <chr> \"D\\u008epart pour la chasse\"\n$ authorstandard    <chr> \"Wouwerman, Philips\"\n$ artistliving      <dbl> 0\n$ authorstyle       <chr> NA\n$ author            <chr> \"Philippe Wouwermans\"\n$ winningbidder     <chr> \"Langlier, Jacques for Poullain, Antoine\"\n$ winningbiddertype <chr> \"DC\"\n$ endbuyer          <chr> \"C\"\n$ Interm            <dbl> 1\n$ type_intermed     <chr> \"D\"\n$ Height_in         <dbl> 17.25\n$ Width_in          <dbl> 23\n$ Surface_Rect      <dbl> 396.75\n$ Diam_in           <dbl> NA\n$ Surface_Rnd       <dbl> NA\n$ Shape             <chr> \"squ_rect\"\n$ Surface           <dbl> 396.75\n$ material          <chr> \"bois\"\n$ mat               <chr> \"b\"\n$ materialCat       <chr> \"wood\"\n$ quantity          <dbl> 1\n$ nfigures          <dbl> 0\n$ engraved          <dbl> 0\n$ original          <dbl> 0\n$ prevcoll          <dbl> 1\n$ othartist         <dbl> 0\n$ paired            <dbl> 1\n$ figures           <dbl> 0\n$ finished          <dbl> 0\n$ lrgfont           <dbl> 0\n$ relig             <dbl> 0\n$ landsALL          <dbl> 1\n$ lands_sc          <dbl> 0\n$ lands_elem        <dbl> 1\n$ lands_figs        <dbl> 1\n$ lands_ment        <dbl> 0\n$ arch              <dbl> 1\n$ mytho             <dbl> 0\n$ peasant           <dbl> 0\n$ othgenre          <dbl> 0\n$ singlefig         <dbl> 0\n$ portrait          <dbl> 0\n$ still_life        <dbl> 0\n$ discauth          <dbl> 0\n$ history           <dbl> 0\n$ allegory          <dbl> 0\n$ pastorale         <dbl> 0\n$ other             <dbl> 0\n```\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell output.lines='[24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44]'}\n::: {.cell-output .cell-output-stdout}\n```\nRows: 1\nColumns: 61\n$ name              <chr> \"R1777-89a\"\n$ sale              <chr> \"R1777\"\n$ lot               <chr> \"89\"\n$ position          <dbl> 0.3755274\n$ dealer            <chr> \"R\"\n$ year              <dbl> 1777\n$ origin_author     <chr> \"D/FL\"\n$ origin_cat        <chr> \"D/FL\"\n$ school_pntg       <chr> \"D/FL\"\n$ diff_origin       <dbl> 0\n$ logprice          <dbl> 8.575462\n$ price             <dbl> 5300\n$ count             <dbl> 1\n$ subject           <chr> \"D\\u008epart pour la chasse\"\n$ authorstandard    <chr> \"Wouwerman, Philips\"\n$ artistliving      <dbl> 0\n$ authorstyle       <chr> NA\n$ author            <chr> \"Philippe Wouwermans\"\n$ winningbidder     <chr> \"Langlier, Jacques for Poullain, Antoine\"\n$ winningbiddertype <chr> \"DC\"\n$ endbuyer          <chr> \"C\"\n$ Interm            <dbl> 1\n$ type_intermed     <chr> \"D\"\n$ Height_in         <dbl> 17.25\n$ Width_in          <dbl> 23\n$ Surface_Rect      <dbl> 396.75\n$ Diam_in           <dbl> NA\n$ Surface_Rnd       <dbl> NA\n$ Shape             <chr> \"squ_rect\"\n$ Surface           <dbl> 396.75\n$ material          <chr> \"bois\"\n$ mat               <chr> \"b\"\n$ materialCat       <chr> \"wood\"\n$ quantity          <dbl> 1\n$ nfigures          <dbl> 0\n$ engraved          <dbl> 0\n$ original          <dbl> 0\n$ prevcoll          <dbl> 1\n$ othartist         <dbl> 0\n$ paired            <dbl> 1\n$ figures           <dbl> 0\n$ finished          <dbl> 0\n$ lrgfont           <dbl> 0\n$ relig             <dbl> 0\n$ landsALL          <dbl> 1\n$ lands_sc          <dbl> 0\n$ lands_elem        <dbl> 1\n$ lands_figs        <dbl> 1\n$ lands_ment        <dbl> 0\n$ arch              <dbl> 1\n$ mytho             <dbl> 0\n$ peasant           <dbl> 0\n$ othgenre          <dbl> 0\n$ singlefig         <dbl> 0\n$ portrait          <dbl> 0\n$ still_life        <dbl> 0\n$ discauth          <dbl> 0\n$ history           <dbl> 0\n$ allegory          <dbl> 0\n$ pastorale         <dbl> 0\n$ other             <dbl> 0\n```\n:::\n:::\n:::\n\n::::\n\n# Modeling the relationship between variables\n\n## Heights\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pp, aes(x = Height_in)) +\n  geom_histogram(binwidth = 5) +\n  labs(x = \"Height, in inches\", y = NULL)\n```\n\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/height-dist-1.png){width=100%}\n:::\n:::\n\n## Widths\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pp, aes(x = Width_in)) +\n  geom_histogram(binwidth = 5) +\n  labs(x = \"Width, in inches\", y = NULL)\n```\n\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/width-dist-1.png){width=100%}\n:::\n:::\n\n\n## Models as functions\n\n- We can represent relationships between variables using **functions**\n- A function is a mathematical concept: the relationship between an output and one or more inputs\n  - Plug in the inputs and receive back the output\n  - Example: The formula $y = 3x + 7$ is a function with input $x$ and output $y$. \n  If $x$ is $5$, $y$ is $22$, $y = 3 \\times 5 + 7 = 22$\n\n## Height as a function of width\n\n::: {.panel-tabset}\n\n### Plot\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/unnamed-chunk-13-1.png){width=100%}\n:::\n:::\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pp, aes(x = Width_in, y = Height_in)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  labs(\n    title = \"Height vs. width of paintings\",\n    subtitle = \"Paris auctions, 1764 - 1780\",\n    x = \"Width (inches)\",\n    y = \"Height (inches)\"\n  )\n```\n:::\n\n:::\n\n## ... without the measure of uncertainty\n\n::: {.panel-tabset}\n\n### Plot\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/unnamed-chunk-14-1.png){width=70%}\n:::\n:::\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pp, aes(x = Width_in, y = Height_in)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", \n              se = FALSE) + #<<\n  labs(\n    title = \"Height vs. width of paintings\",\n    subtitle = \"Paris auctions, 1764 - 1780\",\n    x = \"Width (inches)\",\n    y = \"Height (inches)\"\n  )\n```\n:::\n:::\n\n---\n\n## ... with different cosmetic choices\n\n::: {.panel-tabset}\n### Plot \n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/unnamed-chunk-15-1.png){width=95%}\n:::\n:::\n\n### Code \n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pp, aes(x = Width_in, y = Height_in)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE,\n              color = \"#8E2C90\", linetype = \"dashed\", size = 3) + #<<\n  labs(\n    title = \"Height vs. width of paintings\",\n    subtitle = \"Paris auctions, 1764 - 1780\",\n    x = \"Width (inches)\",\n    y = \"Height (inches)\"\n  )\n```\n:::\n:::\n\n## Other smoothing methods: gam\n\n::: {.panel-tabset}\n\n### Plot\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/unnamed-chunk-16-1.png){width=95%}\n:::\n:::\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pp, aes(x = Width_in, y = Height_in)) +\n  geom_point() +\n  geom_smooth(method = \"gam\", #<<\n              se = FALSE, color = \"#8E2C90\") + \n  labs(\n    title = \"Height vs. width of paintings\",\n    subtitle = \"Paris auctions, 1764 - 1780\",\n    x = \"Width (inches)\",\n    y = \"Height (inches)\"\n  )\n```\n:::\n:::\n\n\n## Other smoothing methods: loess\n\n::: {.panel-tabset}\n### Plot\n\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/unnamed-chunk-17-1.png){width=95%}\n:::\n:::\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pp, aes(x = Width_in, y = Height_in)) +\n  geom_point() +\n  geom_smooth(method = \"loess\", #<<\n              se = FALSE, color = \"#8E2C90\") + \n  labs(\n    title = \"Height vs. width of paintings\",\n    subtitle = \"Paris auctions, 1764 - 1780\",\n    x = \"Width (inches)\",\n    y = \"Height (inches)\"\n  )\n```\n:::\n:::\n\n## Vocabulary\n\n- **Response variable:** Variable whose behavior or variation you are trying to understand, on the y-axis\n\n- **Explanatory variables:** Other variables that you want to use to explain the variation in the response, on the x-axis\n\n- **Predicted value:** Output of the **model function**\n  - The model function gives the typical (expected) value of the response variable *conditioning* on the explanatory variables\n  \n- **Residuals:** A measure of how far each case is from its predicted value (based on a particular model)\n  - Residual = Observed value - Predicted value\n  - Tells how far above/below the expected value each case is\n\n## Residuals {.smaller}\n\n::: {.panel-tabset}\n\n### Plot\n\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/unnamed-chunk-18-1.png){width=100%}\n:::\n:::\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nht_wt_fit <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(Height_in ~ Width_in, data = pp)\n\nht_wt_fit_tidy <- tidy(ht_wt_fit$fit) \nht_wt_fit_aug  <- augment(ht_wt_fit$fit) %>%\n  mutate(res_cat = ifelse(.resid > 0, TRUE, FALSE))\n\nggplot(data = ht_wt_fit_aug) +\n  geom_point(aes(x = Width_in, y = Height_in, color = res_cat)) +\n  geom_line(aes(x = Width_in, y = .fitted), size = 0.75, color = \"#8E2C90\") + \n  labs(\n    title = \"Height vs. width of paintings\",\n    subtitle = \"Paris auctions, 1764 - 1780\",\n    x = \"Width (inches)\",\n    y = \"Height (inches)\"\n  ) +\n  guides(color = \"none\") +\n  scale_color_manual(values = c(\"#260b27\", \"#523178\")) +\n  geom_text(aes(x = 0, y = 150), label = \"Positive residual\", color = \"#e6b0e7\", hjust = 0, size = 8) +\n  geom_text(aes(x = 150, y = 25), label = \"Negative residual\", color = \"#260b27\", hjust = 0, size = 8)\n```\n:::\n:::\n\n\n### Question \nThe plot below displays the relationship between height and width of paintings. The only difference from the previous plots is that it uses a smaller alpha value, making the points somewhat transparent. What feature is apparent in this plot that was not (as) apparent in the previous plots? What might be the reason for this feature?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/height-width-plot-alpha-1.png){width=55%}\n:::\n:::\n\n## Landscape paintings {.smaller}\n\n- Landscape painting is the depiction in art of landscapes – natural scenery such as mountains, valleys, trees, rivers, and forests, especially where the main subject is a wide view – with its elements arranged into a coherent\ncomposition.<sup>1</sup>\n  - Landscape paintings tend to be wider than they are long.\n- Portrait painting is a genre in painting, where the intent is to depict a human subject.<sup>2</sup>\n  - Portrait paintings tend to be longer than they are wide.\n\n::: aside\n[1] Source: Wikipedia, [Landscape painting](https://en.wikipedia.org/wiki/Landscape_painting)\n\n[2] Source: Wikipedia, [Portait painting](https://en.wikipedia.org/wiki/Portrait_painting)\n:::\n\n## Multiple explanatory variables\n\n::: {.panel-tabset}\n\n### Plot\n\n:::: {.columns}\n\n::: {.column width=\"20%\"}\n\n***How, if at all, does the relationship between width and height of paintings vary by whether or not they have any landscape elements?***\n:::\n\n::: {.column width=\"80%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/unnamed-chunk-19-1.png){width=80%}\n:::\n:::\n:::\n\n::::\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pp, aes(x = Width_in, y = Height_in, color = factor(landsALL))) +\n  geom_point(alpha = 0.4) +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(\n    title = \"Height vs. width of paintings, by landscape features\",\n    subtitle = \"Paris auctions, 1764 - 1780\",\n    x = \"Width (inches)\",\n    y = \"Height (inches)\",\n    color = \"landscape\"\n  ) +\n  scale_color_manual(values = c(\"#E48957\", \"#071381\"))\n```\n:::\n:::\n\n\n## Extending regression lines\n\n::: {.panel-tabset}\n\n### Plot\n\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/unnamed-chunk-20-1.png){width=95%}\n:::\n:::\n\n### Code {.smaller}\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pp, aes(x = Width_in, y = Height_in, color = factor(landsALL))) +\n  geom_point(alpha = 0.4) +\n  geom_smooth(method = \"lm\", se = FALSE,\n              fullrange = TRUE) + #<<\n  labs(\n    title = \"Height vs. width of paintings, by landscape features\",\n    subtitle = \"Paris auctions, 1764 - 1780\",\n    x = \"Width (inches)\",\n    y = \"Height (inches)\",\n    color = \"landscape\"\n  ) +\n  scale_color_manual(values = c(\"#E48957\", \"#071381\"))\n```\n:::\n:::\n\n## Models - upsides and downsides\n\n- Models can sometimes reveal patterns that are not evident in a graph of the data. This is a great advantage of modeling over simple visual inspection of data. \n- There is a real risk, however, that a model is imposing structure that is not really there on the scatter of data, just as people imagine animal shapes in the stars. A skeptical approach is always warranted.\n\n## Variation around the model...\n\nis just as important as the model, if not more!  \n\n*Statistics is the explanation of variation in the context of what remains unexplained.*\n\n- The scatter suggests that there might be other factors that account for large parts of painting-to-painting variability, or perhaps just that randomness plays a big role.\n- Adding more explanatory variables to a model can sometimes usefully reduce the size of the scatter around the model. (We'll talk more about this later.)\n\n## How do we use models?\n\n- Explanation: Characterize the relationship between $y$ and $x$ via *slopes* for numerical explanatory variables or *differences* for categorical explanatory variables\n- Prediction: Plug in $x$, get the predicted $y$\n\n---\nformat: revealjs\n---\n\n# Fitting and Interpreting Models\n\n::: {.cell}\n\n:::\n\n\n## Models with numerical explanatory variables\n\n## Data: Paris Paintings {.smaller}\n\n::: {.cell}\n\n```{.r .cell-code}\npp <- read_csv(\"data/paris-paintings.csv\", na = c(\"n/a\", \"\", \"NA\"))\n```\n:::\n\n- Number of observations: 3393\n- Number of variables: 61\n\n\n## Goal: Predict height from width\n\n$$\\widehat{height}_{i} = \\beta_0 + \\beta_1 \\times width_{i}$$\n\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/height-width-plot_2-1.png){width=960}\n:::\n:::\n\n\n## {data-menu-title=\"tidymodels\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/tidymodels.png){width=98%}\n:::\n:::\n\n## Step 1: Specify model\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear Regression Model Specification (regression)\n\nComputational engine: lm \n```\n:::\n:::\n\n## Step 2: Set model fitting *engine*\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") # lm: linear model\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear Regression Model Specification (regression)\n\nComputational engine: lm \n```\n:::\n:::\n\n\n## Step 3: Fit model & estimate parameters\n\n... using **formula syntax**\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(Height_in ~ Width_in, data = pp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nparsnip model object\n\n\nCall:\nstats::lm(formula = Height_in ~ Width_in, data = data)\n\nCoefficients:\n(Intercept)     Width_in  \n     3.6214       0.7808  \n```\n:::\n:::\n\n## A closer look at model output {.bigger}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\nparsnip model object\n\n\nCall:\nstats::lm(formula = Height_in ~ Width_in, data = data)\n\nCoefficients:\n(Intercept)     Width_in  \n     3.6214       0.7808  \n```\n:::\n:::\n\n$$\\widehat{height}_{i} = 3.6214 + 0.7808 \\times width_{i}$$\n\n## A tidy look at model output {.bigger}\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(Height_in ~ Width_in, data = pp) %>%\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 x 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    3.62    0.254        14.3 8.82e-45\n2 Width_in       0.781   0.00950      82.1 0       \n```\n:::\n:::\n\n$$\\widehat{height}_{i} = 3.62 + 0.781 \\times width_{i}$$\n\n## Slope and intercept {.bigger}\n\n$$\\widehat{height}_{i} = 3.62 + 0.781 \\times width_{i}$$\n- **Slope:** For each additional inch the painting is wider, the height is expected to be higher, on average, by 0.781 inches.\n\n- **Intercept:** Paintings that are 0 inches wide are expected to be 3.62 inches high, on average. (Does this make sense?)\n\n## Correlation does not imply causation\n\nRemember this when interpreting model coefficients\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/cell_phones.png){width=90%}\n:::\n:::\n\n::: aside\nSource: XKCD, [Cell phones](https://xkcd.com/925/)\n:::\n\n# Parameter estimation\n\n## Linear model with a single predictor {.smaller}    \n\n- We're interested in $\\beta_0$ (population parameter for the intercept) and $\\beta_1$ (population parameter for the slope) in the following model:\n\n$$\\hat{y}_{i} = \\beta_0 + \\beta_1~x_{i}$$\n- Tough luck, you can't have them...\n\n- So we use sample statistics to estimate them:\n\n$$\\hat{y}_{i} = b_0 + b_1~x_{i}$$\n\n## Least squares regression\n\n- The regression line minimizes the sum of squared residuals.\n- If $e_i = y_i - \\hat{y}_i$, then, the regression line minimizes \n$\\sum_{i = 1}^n e_i^2$.\n\n## Visualizing residuals\n\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/vis-res-1-1.png){width=70%}\n:::\n:::\n\n## Visualizing residuals (cont.)\n\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/vis-res-2-1.png){width=70%}\n:::\n:::\n\n## Visualizing residuals (cont.)\n\n::: {.cell}\n::: {.cell-output-display}\n![](language_fitting_models_files/figure-revealjs/vis-res-3-1.png){width=70%}\n:::\n:::\n\n## Properties of least squares regression {.smaller}\n\n- The regression line goes through the center of mass point, the coordinates corresponding to average $x$ and average $y$, $(\\bar{x}, \\bar{y})$:  \n\n$$\\bar{y} = b_0 + b_1 \\bar{x} ~ \\rightarrow ~ b_0 = \\bar{y} - b_1 \\bar{x}$$\n\n- The slope has the same sign as the correlation coefficient: $b_1 = r \\frac{s_y}{s_x}$\n\n- The sum of the residuals is zero: $\\sum_{i = 1}^n e_i = 0$\n\n- The residuals and $x$ values are uncorrelated\n\n\n## Models with categorical explanatory variables\n\n## Categorical predictor with 2 levels {.smaller}\n\n:::: {.columns}\n\n::: {.column width=\"25%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3,393 x 3\n   name      Height_in landsALL\n   <chr>         <dbl>    <dbl>\n 1 L1764-2          37        0\n 2 L1764-3          18        0\n 3 L1764-4          13        1\n 4 L1764-5a         14        1\n 5 L1764-5b         14        1\n 6 L1764-6           7        0\n 7 L1764-7a          6        0\n 8 L1764-7b          6        0\n 9 L1764-8          15        0\n10 L1764-9a          9        0\n11 L1764-9b          9        0\n12 L1764-10a        16        1\n13 L1764-10b        16        1\n14 L1764-10c        16        1\n15 L1764-11         20        0\n16 L1764-12a        14        1\n17 L1764-12b        14        1\n18 L1764-13a        15        1\n19 L1764-13b        15        1\n20 L1764-14         37        0\n# ... with 3,373 more rows\n```\n:::\n:::\n:::\n\n::: {.column width=\"75%\"}\n\n- `landsALL = 0`: No landscape features\n- `landsALL = 1`: Some landscape features\n:::\n\n::::\n\n## Height & landscape features\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(Height_in ~ factor(landsALL), data = pp) %>%\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 x 5\n  term              estimate std.error statistic  p.value\n  <chr>                <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)          22.7      0.328      69.1 0       \n2 factor(landsALL)1    -5.65     0.532     -10.6 7.97e-26\n```\n:::\n:::\n\n## Height & landscape features\n\n$$\\widehat{Height_{in}} = 22.7 - 5.645~landsALL$$\n\n- **Slope:** Paintings with landscape features are expected, on average, to be 5.645 inches shorter than paintings that without landscape features\n  - Compares baseline level (`landsALL = 0`) to the other level (`landsALL = 1`)\n    \n- **Intercept:** Paintings that don't have landscape features are expected, on average, to be 22.7 inches tall\n\n## Relationship between height and school\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(Height_in ~ school_pntg, data = pp) %>%\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 7 x 5\n  term            estimate std.error statistic p.value\n  <chr>              <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)        14.0       10.0     1.40  0.162  \n2 school_pntgD/FL     2.33      10.0     0.232 0.816  \n3 school_pntgF       10.2       10.0     1.02  0.309  \n4 school_pntgG        1.65      11.9     0.139 0.889  \n5 school_pntgI       10.3       10.0     1.02  0.306  \n6 school_pntgS       30.4       11.4     2.68  0.00744\n7 school_pntgX        2.87      10.3     0.279 0.780  \n```\n:::\n:::\n\n## Dummy variables\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 7 x 5\n  term            estimate std.error statistic p.value\n  <chr>              <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)        14.0       10.0     1.40  0.162  \n2 school_pntgD/FL     2.33      10.0     0.232 0.816  \n3 school_pntgF       10.2       10.0     1.02  0.309  \n4 school_pntgG        1.65      11.9     0.139 0.889  \n5 school_pntgI       10.3       10.0     1.02  0.306  \n6 school_pntgS       30.4       11.4     2.68  0.00744\n7 school_pntgX        2.87      10.3     0.279 0.780  \n```\n:::\n:::\n\n- When the categorical explanatory variable has many levels, they're encoded to **dummy variables**\n- Each coefficient describes the expected difference between heights in that particular school compared to the baseline level\n\n\n## Categorical predictor with 3+ levels {.smaller}\n\n::: {.panel-tabset}\n\n### Comparison\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> school_pntg </th>\n   <th style=\"text-align:center;\"> D_FL </th>\n   <th style=\"text-align:center;\"> F </th>\n   <th style=\"text-align:center;\"> G </th>\n   <th style=\"text-align:center;\"> I </th>\n   <th style=\"text-align:center;\"> S </th>\n   <th style=\"text-align:center;\"> X </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> A </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> D/FL </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;\"> 1 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> F </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;\"> 1 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> G </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;\"> 1 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> I </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;\"> 1 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> S </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;\"> 1 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> X </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;\"> 0 </td>\n   <td style=\"text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;\"> 1 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n### R Output\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3,393 x 3\n   name      Height_in school_pntg\n   <chr>         <dbl> <chr>      \n 1 L1764-2          37 F          \n 2 L1764-3          18 I          \n 3 L1764-4          13 D/FL       \n 4 L1764-5a         14 F          \n 5 L1764-5b         14 F          \n 6 L1764-6           7 I          \n 7 L1764-7a          6 F          \n 8 L1764-7b          6 F          \n 9 L1764-8          15 I          \n10 L1764-9a          9 D/FL       \n11 L1764-9b          9 D/FL       \n12 L1764-10a        16 X          \n13 L1764-10b        16 X          \n14 L1764-10c        16 X          \n15 L1764-11         20 D/FL       \n16 L1764-12a        14 D/FL       \n17 L1764-12b        14 D/FL       \n18 L1764-13a        15 D/FL       \n19 L1764-13b        15 D/FL       \n20 L1764-14         37 F          \n# ... with 3,373 more rows\n```\n:::\n:::\n:::\n\n## {data-menu-title=\"Height vs school\" .smaller}\n### Relationship between height and school \n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 7 x 5\n  term            estimate std.error statistic p.value\n  <chr>              <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)        14.0       10.0     1.40  0.162  \n2 school_pntgD/FL     2.33      10.0     0.232 0.816  \n3 school_pntgF       10.2       10.0     1.02  0.309  \n4 school_pntgG        1.65      11.9     0.139 0.889  \n5 school_pntgI       10.3       10.0     1.02  0.306  \n6 school_pntgS       30.4       11.4     2.68  0.00744\n7 school_pntgX        2.87      10.3     0.279 0.780  \n```\n:::\n:::\n\n- **Austrian school (A)** paintings are expected, on average, to be **14 inches** tall.\n- **Dutch/Flemish school (D/FL)** paintings are expected, on average, to be **2.33 inches taller** than *Austrian school* paintings.\n- **French school (F)** paintings are expected, on average, to be **10.2 inches taller** than *Austrian school* paintings.\n- **German school (G)** paintings are expected, on average, to be **1.65 inches taller** than *Austrian school* paintings.\n- **Italian school (I)** paintings are expected, on average, to be **10.3 inches taller** than *Austrian school* paintings.\n- **Spanish school (S)** paintings are expected, on average, to be **30.4 inches taller** than *Austrian school* paintings.\n- Paintings whose school is **unknown (X)** are expected, on average, to be **2.87 inches taller** than *Austrian school* paintings.\n\n\n",
    "supporting": [
      "language_fitting_models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\r\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\r\n"
      ],
      "include-after-body": [
        "\r\n<script>\r\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\r\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\r\n  // slide changes (different for each slide format).\r\n  (function () {\r\n    function fireSlideChanged(previousSlide, currentSlide) {\r\n\r\n      // dispatch for htmlwidgets\r\n      const event = window.document.createEvent(\"Event\");\r\n      event.initEvent(\"slideenter\", true, true);\r\n      window.document.dispatchEvent(event);\r\n\r\n      // dispatch for shiny\r\n      if (window.jQuery) {\r\n        if (previousSlide) {\r\n          window.jQuery(previousSlide).trigger(\"hidden\");\r\n        }\r\n        if (currentSlide) {\r\n          window.jQuery(currentSlide).trigger(\"shown\");\r\n        }\r\n      }\r\n    }\r\n\r\n    // hookup for reveal\r\n    if (window.Reveal) {\r\n      window.Reveal.addEventListener(\"slidechanged\", function(event) {\r\n        fireSlideChanged(event.previousSlide, event.currentSlide);\r\n      });\r\n    }\r\n\r\n    // hookup for slidy\r\n    if (window.w3c_slidy) {\r\n      window.w3c_slidy.add_observer(function (slide_num) {\r\n        // slide_num starts at position 1\r\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\r\n      });\r\n    }\r\n\r\n  })();\r\n</script>\r\n\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}